version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: runnerexplorer
      MYSQL_DATABASE: runner_explorer
      MYSQL_USER: runnerexplorer
      MYSQL_PASSWORD: runnerexplorer
    ports:
      - "3307:3306"
    volumes:
      - ./src/config/schema_dump.sql:/docker-entrypoint-initdb.d/schema_dump.sql:ro  
      - mysql_data:/var/lib/mysql                             

volumes:
  mysql_data: